[tool.poetry]
name = "biscuit"
version = "2.33.0"
description = "The uncompromising code editor"
authors = ["Billy <billydevbusiness@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
hintedtext = "^0.6.0"
watchdog = "^3.0.0"
filetype = "^1.2.0"
GitPython = "^3.1.40"
tkextrafont = "^0.6.3"
Pygments = "^2.17.1"
toml = "^0.10.2"
sv-ttk = "^2.5.5"
Pillow = "^10.1.0"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-dotenv = "^0.5.2"
git-changelog = "^2.4.0"
pyperclip = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
